export const userData = [
  {
    firstname: { value: "john", isChecked: false },
    lastname: { value: "stewart", isChecked: false },
    birthdate: { value: "1991/01/13", isChecked: false },
    id: { value: "4980011111", isChecked: false },
    mobile: { value: "4980011111", isChecked: false },
    imgSrc: { value: "/images/user-1.png", isChecked: false },
    address: { value: "No. 58 Goldensmith St,London,U.K", isChecked: false },
    isChecked: false,
    isSelected: false,
  },
  {
    firstname: { value: "jack", isChecked: false },
    lastname: { value: "stewart", isChecked: false },
    birthdate: { value: "1991/01/13", isChecked: false },
    id: { value: "4980011112", isChecked: false },
    mobile: { value: "4980011112", isChecked: false },
    imgSrc: { value: "/images/user-2.png", isChecked: false },
    address: { value: "No. 58 Goldensmith St,London,U.K", isChecked: false },
    isChecked: false,
    isSelected: false,
  },
  {
    firstname: { value: "natalia", isChecked: false },
    lastname: { value: "gomez", isChecked: false },
    birthdate: { value: "1986/06/06", isChecked: false },
    id: { value: "8463830885", isChecked: false },
    mobile: { value: "8463830885", isChecked: false },
    imgSrc: { value: "/images/user-3.png", isChecked: false },
    address: { value: "No. 58 Goldensmith St,London,U.K", isChecked: false },
    isChecked: false,
    isSelected: false,
  },
];
